name: Coverage

on:
  push:
    branches:
      - '2.*'
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - reopened

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      # Configure PHP
      - name: Select PHP version
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.3'
          extensions: mbstring, pdo_sqlite, fileinfo, gd
          coverage: pcov

      # Configure NPM
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      # Install PHP dependencies
      - name: Install Composer dependencies
        run: composer require "illuminate/support:7.*"
      
      # Make sure the proper Chromedriver for Dusk is installed
      - name: Install Chromedriver for Dusk
        run: ./vendor/bin/dusk-updater detect --auto-update

      # Install NPM dependencies
      - name: Install Dependencies
        run: npm install

      # Build static assets
      - name: Compile Assets
        run: npm run prod

      # Run phpunit tests to generate coverage report
      #- name: Run tests for coverage
      #  run: php -d pcov.enabled=1 ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: d7ac50851610b4bfae417c6942bba6a399435943951ee9c1fb470ad29c94f0ed
        with:
          coverageCommand: php -d pcov.enabled=1 ./vendor/bin/phpunit --coverage-clover=coverage.xml

      # Upload coverage report to codecov.io
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
