name: Tests

on:
  push:
    branches:
      - '2.*'
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - reopened

jobs:
  compile-assets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Configure NPM
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      # Install NPM dependencies
      - name: Install Dependencies
        run: npm install

      # Build static assets
      - name: Compile Assets
        run: npm run prod

  run-tests:
    needs: compile-assets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        laravel: [7.*, 8.*]
        php: [7.3, 7.4, 8.0]

    steps:
      - uses: actions/checkout@master
      # Configure PHP
      - name: Select PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo_sqlite, fileinfo, gd
          tools: composer:v2

      # Install PHP dependencies
      - name: Install Composer dependencies
        run: composer require "illuminate/support:${{ matrix.laravel }}"

      # Run tests
      - name: Run tests
        run: ./vendor/bin/phpunit --no-coverage